channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==3.1.1
  - google-cloud-storage==3.1.0
  - keras==3.8.0
  - numpy==1.26.4
  - tensorflow-intel==2.18.0
name: mlflow-env
